on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

name: thrive-frontend

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: google-github-actions/release-please-action@v3
              env:
                GITHUB_TOKEN: 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
              with:
                  release-type: node
                  package-name: release-please-action
                  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
